Mfrp_CorporateClassifieds-Initial/CorporateClassifieds/CLassifiedsUIPortal/CLassifiedsUIPortal/Models/OfferHelper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace CLassifiedsUIPortal.Models
{
    public class OfferHelper
    {
        public HttpClient Initial()
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44389/");
            return client;
        }
    }
}

Mfrp_CorporateClassifieds-Initial/CorporateClassifieds/CLassifiedsUIPortal/CLassifiedsUIPortal/Controllers/OfferController.cs
using CLassifiedsUIPortal.Models;
using CLassifiedsUIPortal.Provider;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace CLassifiedsUIPortal.Controllers
{
    public class OfferController : Controller
    {
        // GET: EmployeeController
        OfferHelper _api = new OfferHelper();

        private log4net.ILog _logger = log4net.LogManager.GetLogger(typeof(OfferController));
        private readonly IOfferProvider _provider;
        public OfferController(IOfferProvider provider)
        {
            this._provider = provider;
        }

        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            return View();
        }
        public ActionResult GetId(int Id)
        {

            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }

            return View();
        }

        public IActionResult NoOffer()
        {
            _logger.Info(" There is No such Product To display");
            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> GetOfferById(int Id)
        {

            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            else
            {
                var offer = new OfferData();


                try
                {
                    string token = HttpContext.Session.GetString("token");
                    var response = await _provider.GetOfferById(Id, token);

                    if (response.IsSuccessStatusCode)
                    {
                        var JsonContent = await response.Content.ReadAsStringAsync();
                        offer = JsonConvert.DeserializeObject<OfferData>(JsonContent);
                        return View(offer);
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                    {
                        ViewBag.Message = "No any record Found! Bad Request";
                        return RedirectToAction("NoOffer");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                    {
                        ViewBag.Message = "Having server issue while adding record";
                        return RedirectToAction("NoOffer");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                    {
                        ViewBag.Message = "No record found in DB for ID :" + Id;
                        return RedirectToAction("NoOffer");
                    }
                }
                catch (Exception e)
                {
                    _logger.Error("Exception occured as :" + e.Message);
                }
                return View(offer);
            }
        }

        /*
        var offers = new OfferData();
        HttpClient client = _api.Initial();
        HttpResponseMessage httpResponseMessage = await client.GetAsync($"api/offer/GetOfferById/{Id}");
        if(httpResponseMessage.IsSuccessStatusCode)
        {
            var results = httpResponseMessage.Content.ReadAsStringAsync().Result;
            offers = JsonConvert.DeserializeObject<OfferData>(results);
        }

        return View(offers);
        */

        public ActionResult GetCategory(string category)
        {

            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetOfferByCategory(string category)
        {

            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            else
            {
                List<OfferData> offer = new List<OfferData>();


                try
                {
                    string token = HttpContext.Session.GetString("token");
                    var response = await _provider.GetOfferByCategory(category, token);

                    if (response.IsSuccessStatusCode)
                    {
                        var JsonContent = await response.Content.ReadAsStringAsync();
                        offer = JsonConvert.DeserializeObject<List<OfferData>>(JsonContent);
                        return View(offer);
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                    {
                        ViewBag.Message = "No any record Found! Bad Request";
                        return RedirectToAction("NoOffer");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                    {
                        ViewBag.Message = "Having server issue while adding record";
                        return RedirectToAction("NoOffer");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                    {
                        ViewBag.Message = "No record found in DB for Category :" + category;
                        return RedirectToAction("NoOffer");
                    }
                }
                catch (Exception e)
                {
                    _logger.Error("Exception occured as :" + e.Message);
                }
                return View(offer.AsEnumerable());
            }
        }


        public ActionResult GetTopThreeLikes(string category)
        {

            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }

            return View();
        }


        [HttpGet]
        public async Task<IActionResult> GetOfferByTopThreeLikes(string category)
        {

            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            else
            {
                List<OfferData> offer = new List<OfferData>();


                try
                {
                    string token = HttpContext.Session.GetString("token");
                    var response = await _provider.GetOfferByTopThreeLikes(category, token);

                    if (response.IsSuccessStatusCode)
                    {
                        var JsonContent = await response.Content.ReadAsStringAsync();
                        offer = JsonConvert.DeserializeObject<List<OfferData>>(JsonContent);
                        return View(offer);
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                    {
                        ViewBag.Message = "No any record Found! Bad Request";
                        return RedirectToAction("NoOffer");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                    {
                        ViewBag.Message = "Having server issue while adding record";
                        return RedirectToAction("NoOffer");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                    {
                        ViewBag.Message = "No record found in DB for Category :" + category;
                        return RedirectToAction("NoOffer");
                    }
                }
                catch (Exception e)
                {
                    _logger.Error("Exception occured as :" + e.Message);
                }
                return View(offer.AsEnumerable());
            }
        }

        public ActionResult GetByOpenedDate(DateTime openedDate)
        {

            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetOfferByOpenedDate(DateTime openedDate)
        {
            string sd = openedDate.ToString("dd-MM-yyyyy");


            //DateTime sd1 = DateTime.Parse(sd);

            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            else
            {
                List<OfferData> offer = new List<OfferData>();


                try
                {
                    string token = HttpContext.Session.GetString("token");
                    var response = await _provider.GetOfferByOpenedDate(sd, token);

                    if (response.IsSuccessStatusCode)
                    {
                        var JsonContent = await response.Content.ReadAsStringAsync();
                        offer = JsonConvert.DeserializeObject<List<OfferData>>(JsonContent);
                        return View(offer);
                    }

                    else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                    {
                        ViewBag.Message = "No any record Found! Bad Request";
                        return RedirectToAction("NoOffer");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                    {

Mfrp_CorporateClassifieds-Initial/CorporateClassifieds/CLassifiedsUIPortal/CLassifiedsUIPortal/Controllers/PointsController.cs
using CLassifiedsUIPortal.Models;
using CLassifiedsUIPortal.Provider;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace CLassifiedsUIPortal.Controllers
{
    public class PointsController : Controller
    {

        PointsHelper _api = new PointsHelper();

        private log4net.ILog _logger = log4net.LogManager.GetLogger(typeof(EmployeeController));
        private readonly IPointsProvider _provider;
        public PointsController(IPointsProvider provider)
        {
            this._provider = provider;
        }
     



        [HttpGet]
        public async Task<ActionResult> GetPointsByEmployeeId()
        {

            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            else
            {
                var points = new PointsData();
               
                
                points.EmployeeId = Convert.ToInt32(HttpContext.Session.GetInt32("EmployeeId"));


                try
                {
                    string token = HttpContext.Session.GetString("token");
                    var response = await _provider.GetPointsByEmployeeId(points.EmployeeId, token);
                   

                    if (response.IsSuccessStatusCode)
                    {
                        var JsonContent = await response.Content.ReadAsStringAsync();
                        points = JsonConvert.DeserializeObject<PointsData>(JsonContent);
                        return View(points);
                    }
                    /*
                    else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                    {
                        ViewBag.Message = "No any record Found! Bad Request";
                        return RedirectToAction("NoEmployee");
                    }
                
                    else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                    {
                        //ViewBag.Message = "No Offers found for Employee :" + employee.EmployeeId;
                        return RedirectToAction("NoEmployee");
                    }
                    */
                }
                catch (Exception e)
                {
                    _logger.Error("Exception occured as :" + e.Message);
                }
                return View(points);

            }
        }

        [HttpGet]
        public async Task<ActionResult> RefreshPointsByEmployee()
        {

            if (HttpContext.Session.GetString("token") == null)
            {
                return RedirectToAction("Login", "Auth");
            }
            else
            {
                var points = new PointsData();


                points.EmployeeId = Convert.ToInt32(HttpContext.Session.GetInt32("EmployeeId"));


                try
                {
                    string token = HttpContext.Session.GetString("token");
                    var response = await _provider.RefreshPointsByEmployee(points.EmployeeId, token);


                    if (response.IsSuccessStatusCode)
                    {
                        var JsonContent = await response.Content.ReadAsStringAsync();
                        points = JsonConvert.DeserializeObject<PointsData>(JsonContent);
                        ViewBag.Message = "Points Updated";
                        return View(points);
                    }
                    /*
                    else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                    {
                        ViewBag.Message = "No any record Found! Bad Request";
                        return RedirectToAction("NoEmployee");
                    }
                
                    else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                    {
                        //ViewBag.Message = "No Offers found for Employee :" + employee.EmployeeId;
                        return RedirectToAction("NoEmployee");
                    }
                    */
                }
                catch (Exception e)
                {
                    _logger.Error("Exception occured as :" + e.Message);
                }
                return View(points);

            }
        }
       

        }
}

Mfrp_CorporateClassifieds-Initial/CorporateClassifieds/CLassifiedsUIPortal/CLassifiedsUIPortal/Views/Offer/GetByOpenedDate.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>Corporate Classifieds</title>

    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">



    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-style.css">


</head>

<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Main -->
        <div id="main">
            <div class="inner">

                <!-- Header -->
                <header id="header">
                    <div class="logo">
                        <a href="index.html">Corporate Classifieds</a>
                    </div>
                </header>

                <!-- Banner -->
                <!-- Search Box -->


                <form action="GetOfferByOpenedDate" method="get">

                    <h4>Get Offer Details Posted Date</h4>

                    <div class="input-group">

                        <input type="date" class="form-control rounded" placeholder="Enter Posted Date(YYYY-MM-DD)" name="openedDate" aria-label="Search" aria-describedby="search-addon" required />
                        <button type="submit" class="btn btn-outline-primary">search</button>
                    </div>
                </form>


            </div>
        </div>

        <!-- Sidebar -->
        <div id="sidebar">

            <div class="inner">

                <!-- Menu -->
                <nav id="menu">
                    <ul>
                        <li><a href="@Url.Action("GetOffersList", "Home")">Home</a></li>
                        <li>
                            <span class="opener">Offers</span>
                            <ul>
                                <li><a href="@Url.Action("GetId", "Offer")">Offer Details by Id</a></li>
                                <li><a href="@Url.Action("GetCategory", "Offer")">Offer Details by Category</a></li>
                                <li><a href="@Url.Action("GetTopThreeLikes", "Offer")">Offer by Top 3 Likes</a></li>
                                <li><a href="@Url.Action("GetByOpenedDate", "Offer")">Offer by Posted Date</a></li>
                                <li><a href="@Url.Action("EngageOffer", "Offer")">Engage Offer </a></li>
                                <li><a href="@Url.Action("GetIdForEditOffer", "Offer")">Edit Offer</a></li>
                                <li><a href="@Url.Action("PostOffer", "Offer")">Add Offer</a></li>
                            </ul>
                        </li>
                        <li>
                            <span class="opener">Employee</span>
                            <ul>
                                <li><a href="@Url.Action("ViewEmployeeOffers", "Employee")">View Employee Offers</a></li>
                                <li><a href="@Url.Action("ViewMostLikedOffers", "Employee")">View Most Liked Offers</a></li>
                                <li><a href="@Url.Action("ViewEmployeeProfile", "Employee")">View Profile</a></li>
                            </ul>
                        </li>
                        <li>
                            <span class="opener">Points</span>
                            <ul>
                                <li><a href="@Url.Action("GetPointsByEmployeeId", "Points")">Get Points of Employee</a></li>
                                <li><a href="@Url.Action("RefreshPointsByEmployee", "Points")">Refresh Points of Employee</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Logout</a></li>
                    </ul>
                </nav>


            </div>
        </div>

    </div>

    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/assets/js/browser.min.js"></script>
    <script src="~/assets/js/breakpoints.min.js"></script>
    <script src="~/assets/js/transition.js"></script>
    <script src="~/assets/js/owl-carousel.js"></script>
    <script src="~/assets/js/custom.js"></script>
</body>




</html>

Mfrp_CorporateClassifieds-Initial/CorporateClassifieds/CLassifiedsUIPortal/CLassifiedsUIPortal/Views/Offer/GetCategory.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>Corporate Classifieds</title>

    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">



    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-style.css">


</head>

<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Main -->
        <div id="main">
            <div class="inner">

                <!-- Header -->
                <header id="header">
                    <div class="logo">
                        <a href="index.html">Corporate Classifieds</a>
                    </div>
                </header>

                <!-- Banner -->
                <!-- Search Box -->


                <form action="GetOfferByCategory" method="get">

                    <h4>Get Offer Details by Category:</h4>

                    <div class="input-group">

                        <input type="text" class="form-control rounded" placeholder="Enter Offer Category..." name="category" aria-label="Search" aria-describedby="search-addon" required/>
                        <button type="submit" class="btn btn-outline-primary">search</button>
                    </div>
                </form>


            </div>
        </div>

        <!-- Sidebar -->
        <div id="sidebar">

            <div class="inner">

                <!-- Menu -->
                <nav id="menu">
                    <ul>
                        <li><a href="@Url.Action("GetOffersList", "Home")">Home</a></li>
                        <li>
                            <span class="opener">Offers</span>
                            <ul>
                                <li><a href="@Url.Action("GetId", "Offer")">Offer Details by Id</a></li>
                                <li><a href="@Url.Action("GetCategory", "Offer")">Offer Details by Category</a></li>
                                <li><a href="@Url.Action("GetTopThreeLikes", "Offer")">Offer by Top 3 Likes</a></li>
                                <li><a href="@Url.Action("GetByOpenedDate", "Offer")">Offer by Posted Date</a></li>
                                <li><a href="@Url.Action("EngageOffer", "Offer")">Engage Offer </a></li>
                                <li><a href="@Url.Action("GetIdForEditOffer", "Offer")">Edit Offer</a></li>
                                <li><a href="@Url.Action("PostOffer", "Offer")">Add Offer</a></li>
                            </ul>
                        </li>
                        <li>
                            <span class="opener">Employee</span>
                            <ul>
                                <li><a href="@Url.Action("ViewEmployeeOffers", "Employee")">View Employee Offers</a></li>
                                <li><a href="@Url.Action("ViewMostLikedOffers", "Employee")">View Most Liked Offers</a></li>
                                <li><a href="@Url.Action("ViewEmployeeProfile", "Employee")">View Profile</a></li>
                            </ul>
                        </li>
                        <li>
                            <span class="opener">Points</span>
                            <ul>
                                <li><a href="@Url.Action("GetPointsByEmployeeId", "Points")">Get Points of Employee</a></li>
                                <li><a href="@Url.Action("RefreshPointsByEmployee", "Points")">Refresh Points of Employee</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Logout</a></li>
                    </ul>
                </nav>


            </div>
        </div>

    </div>

    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/assets/js/browser.min.js"></script>
    <script src="~/assets/js/breakpoints.min.js"></script>
    <script src="~/assets/js/transition.js"></script>
    <script src="~/assets/js/owl-carousel.js"></script>
    <script src="~/assets/js/custom.js"></script>
</body>




</html>

Mfrp_CorporateClassifieds-Initial/CorporateClassifieds/CLassifiedsUIPortal/CLassifiedsUIPortal/Views/Offer/GetId.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>Corporate Classifieds</title>

    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">



    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-style.css">
    

</head>

<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Main -->
        <div id="main">
            <div class="inner">

                <!-- Header -->
                <header id="header">
                    <div class="logo">
                        <a href="index.html">Corporate Classifieds</a>
                    </div>
                </header>

                <!-- Banner -->
                <!-- Search Box -->
                
                
                <form action="GetOfferById" method="get">

                    <h4>Get Offer Details by Id:</h4>

                    <div class="input-group">

                        <input type="text" class="form-control rounded" placeholder="Enter Offer Id..." name="id" aria-label="Search" aria-describedby="search-addon" required />
                        <button type="submit" class="btn btn-outline-primary" >search</button>
                    </div>
                </form>
                

</div>
        </div>

        <!-- Sidebar -->
        <div id="sidebar">

            <div class="inner">

                <!-- Menu -->
                <nav id="menu">
                    <ul>
                        <li><a href="@Url.Action("GetOffersList", "Home")">Home</a></li>
                        <li>
                            <span class="opener">Offers</span>
                            <ul>
                                <li><a href="@Url.Action("GetId", "Offer")">Offer Details by Id</a></li>
                                <li><a href="@Url.Action("GetCategory", "Offer")">Offer Details by Category</a></li>
                                <li><a href="@Url.Action("GetTopThreeLikes", "Offer")">Offer by Top 3 Likes</a></li>
                                <li><a href="@Url.Action("GetByOpenedDate", "Offer")">Offer by Posted Date</a></li>
                                <li><a href="@Url.Action("EngageOffer", "Offer")">Engage Offer </a></li>
                                <li><a href="@Url.Action("GetIdForEditOffer", "Offer")">Edit Offer</a></li>
                                <li><a href="@Url.Action("PostOffer", "Offer")">Add Offer</a></li>
                            </ul>
                        </li>
                        <li>
                            <span class="opener">Employee</span>
                            <ul>
                                <li><a href="@Url.Action("ViewEmployeeOffers", "Employee")">View Employee Offers</a></li>
                                <li><a href="@Url.Action("ViewMostLikedOffers", "Employee")">View Most Liked Offers</a></li>
                                <li><a href="@Url.Action("ViewEmployeeProfile", "Employee")">View Profile</a></li>
                            </ul>
                        </li>
                        <li>
                            <span class="opener">Points</span>
                            <ul>
                                <li><a href="@Url.Action("GetPointsByEmployeeId", "Points")">Get Points of Employee</a></li>
                                <li><a href="@Url.Action("RefreshPointsByEmployee", "Points")">Refresh Points of Employee</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Logout</a></li>
                    </ul>
                </nav>


            </div>
        </div>

    </div>

    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/assets/js/browser.min.js"></script>
    <script src="~/assets/js/breakpoints.min.js"></script>
    <script src="~/assets/js/transition.js"></script>
    <script src="~/assets/js/owl-carousel.js"></script>
    <script src="~/assets/js/custom.js"></script>
</body>


 

</html>

Mfrp_CorporateClassifieds-Initial/CorporateClassifieds/CLassifiedsUIPortal/CLassifiedsUIPortal/Views/Offer/NoOffer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{ ViewData["Title"] = "NoOffer";

}
<!DOCTYPE html>
<html lang="en">

<head>

    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">



    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-style.css">
    <link rel="stylesheet" href="~/assets/css/owl.css">
</head>
<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Main -->
        <div id="main">
            <div class="inner">
                <!-- Header -->
                <header id="header">
                    <div class="logo">
                        <a href="index.html">Corporate Classifieds</a>
                    </div>
                </header>

                <div style="margin-left:30%">
                    <br />
                    <br />
                    <br />
                    <br />

                    <h1>
                        There is No such Offer,<br />
                        Would you like to search for other Offer?
                    </h1>
                    <br />
                    <br />
                    <a class="btn btn-primary btn-lg" href="@Url.Action("GetId", "Offer")">Yes</a>
                    <a class="btn btn-primary btn-lg" style="margin-left:3%" href="@Url.Action("Index","Offer")">No</a>
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />

                </div>
            </div>
        </div>
    </div>
</body>
</html>